//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_AOwn.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter Your UserName")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Enter Your Password")]
        public string Password { get; set; }
    }
}
