//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_AOwn.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donar
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Enter Your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Your Contact Number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Enter Your Valid Email Addreess")]
        [EmailAddress]
        public string Email { get; set; }
        [Range(100,10000000000000,ErrorMessage ="Minimum Donation is 100 Taka")]
        public int Amount { get; set; }
        [Required(ErrorMessage = "Enter Your Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Enter Your thought about this donation")]
        public string Comment { get; set; }
    }
}
