//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_AOwn.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Receiver
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Enter Your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Phone Number")]
        public string Phone { get; set; }
        [Range(0,15000,ErrorMessage ="Crossed The Maximun Limit")]
        public int RAmount { get; set; }
        [Required(ErrorMessage ="Give a Brief Discussion About Your Situation")]
        public string Comment { get; set; }
    }
}
