//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_performance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P_PEntities : DbContext
    {
        public P_PEntities()
            : base("name=P_PEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Donar> Donars { get; set; }
        public DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<Class_performance.Models.Membership> Memberships { get; set; }
    }
}
