//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Try_ThreadStone.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donar
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
        public string Address { get; set; }
        public string BGroup { get; set; }
        public string Comments { get; set; }
    }
}
